from setuptools import setup
 
setup(
    name='SEA2017',
    version='V1.0',
    packages=['com', 'com.nrtest', 'com.nrtest.sea', 'com.nrtest.sea.data', 'com.nrtest.sea.data.common',
              'com.nrtest.sea.data.adv_app', 'com.nrtest.sea.data.adv_app.appDispose',
              'com.nrtest.sea.data.adv_app.lowCollect', 'com.nrtest.sea.data.adv_app.newsanswer',
              'com.nrtest.sea.data.adv_app.vipConsMan', 'com.nrtest.sea.data.adv_app.vipConsMan.distributedEnergyMange',
              'com.nrtest.sea.data.adv_app.dataRecover', 'com.nrtest.sea.data.adv_app.intelligentLock',
              'com.nrtest.sea.data.adv_app.lineLossAnalysis', 'com.nrtest.sea.data.adv_app.costControlManage',
              'com.nrtest.sea.data.adv_app.costControlManage.remoteCustControl',
              'com.nrtest.sea.data.adv_app.orderedElectricity', 'com.nrtest.sea.data.adv_app.transformerMonitor',
              'com.nrtest.sea.data.adv_app.meteringOnlineMonitor', 'com.nrtest.sea.data.run_man',
              'com.nrtest.sea.data.run_man.clock', 'com.nrtest.sea.data.run_man.groupMan',
              'com.nrtest.sea.data.run_man.meterMan', 'com.nrtest.sea.data.run_man.simCardMan',
              'com.nrtest.sea.data.run_man.operOrganMan', 'com.nrtest.sea.data.run_man.runStatusMonitor',
              'com.nrtest.sea.data.sys_mam', 'com.nrtest.sea.data.sys_mam.logMan',
              'com.nrtest.sea.data.sys_mam.msgPush', 'com.nrtest.sea.data.sys_mam.sysUseStat',
              'com.nrtest.sea.data.sys_mam.securityMan', 'com.nrtest.sea.data.sys_mam.templateMan',
              'com.nrtest.sea.data.sys_mam.sysConfigMan', 'com.nrtest.sea.data.base_app',
              'com.nrtest.sea.data.base_app.custMan', 'com.nrtest.sea.data.base_app.archivesMan',
              'com.nrtest.sea.data.base_app.terminalMan', 'com.nrtest.sea.data.base_app.interfaceMan',
              'com.nrtest.sea.data.base_app.dataGatherMan', 'com.nrtest.sea.data.base_app.multiTableOne',
              'com.nrtest.sea.data.stat_rey', 'com.nrtest.sea.data.stat_rey.reportMan',
              'com.nrtest.sea.data.stat_rey.workQuery', 'com.nrtest.sea.data.stat_rey.synthQuery',
              'com.nrtest.sea.data.stat_rey.dataAnalyse', 'com.nrtest.sea.data.stat_rey.dataAnalyse.loadAanlyse',
              'com.nrtest.sea.data.stat_rey.collConstructStatus', 'com.nrtest.sea.data.testMethodPara',
              'com.nrtest.sea.task', 'com.nrtest.sea.pages', 'com.nrtest.sea.pages.other',
              'com.nrtest.sea.pages.adv_app', 'com.nrtest.sea.pages.adv_app.appDispose',
              'com.nrtest.sea.pages.adv_app.lowCollect', 'com.nrtest.sea.pages.adv_app.newsanswer',
              'com.nrtest.sea.pages.adv_app.vipConsMan',
              'com.nrtest.sea.pages.adv_app.vipConsMan.distributedEnergyMange',
              'com.nrtest.sea.pages.adv_app.dataRecover', 'com.nrtest.sea.pages.adv_app.intelligentLock',
              'com.nrtest.sea.pages.adv_app.lineLossAnalysis', 'com.nrtest.sea.pages.adv_app.costControlManage',
              'com.nrtest.sea.pages.adv_app.costControlManage.remoteCustControl',
              'com.nrtest.sea.pages.adv_app.orderedElectricity', 'com.nrtest.sea.pages.adv_app.transformerMonitor',
              'com.nrtest.sea.pages.adv_app.meteringOnlineMonitor', 'com.nrtest.sea.pages.run_man',
              'com.nrtest.sea.pages.run_man.clock', 'com.nrtest.sea.pages.run_man.groupMan',
              'com.nrtest.sea.pages.run_man.meterMan', 'com.nrtest.sea.pages.run_man.simCardMan',
              'com.nrtest.sea.pages.run_man.operOrganMan', 'com.nrtest.sea.pages.run_man.runStatusMonitor',
              'com.nrtest.sea.pages.sys_mam', 'com.nrtest.sea.pages.sys_mam.logMan',
              'com.nrtest.sea.pages.sys_mam.msgPush', 'com.nrtest.sea.pages.sys_mam.sysUseStat',
              'com.nrtest.sea.pages.sys_mam.securityMan', 'com.nrtest.sea.pages.sys_mam.templateMan',
              'com.nrtest.sea.pages.sys_mam.sysConfigMan', 'com.nrtest.sea.pages.base_app',
              'com.nrtest.sea.pages.base_app.custMan', 'com.nrtest.sea.pages.base_app.archivesMan',
              'com.nrtest.sea.pages.base_app.terminalMan', 'com.nrtest.sea.pages.base_app.interfaceMan',
              'com.nrtest.sea.pages.base_app.dataGatherMan',
              'com.nrtest.sea.pages.base_app.dataGatherMan.gatherQualityAnalyze',
              'com.nrtest.sea.pages.base_app.multiTableOne', 'com.nrtest.sea.pages.stat_rey',
              'com.nrtest.sea.pages.stat_rey.reportMan', 'com.nrtest.sea.pages.stat_rey.workQuery',
              'com.nrtest.sea.pages.stat_rey.synthQuery', 'com.nrtest.sea.pages.stat_rey.dataAnalyse',
              'com.nrtest.sea.pages.stat_rey.dataAnalyse.loadAanyse',
              'com.nrtest.sea.pages.stat_rey.collConstructStatus', 'com.nrtest.sea.locators',
              'com.nrtest.sea.locators.other', 'com.nrtest.sea.locators.adv_app',
              'com.nrtest.sea.locators.adv_app.appDispose', 'com.nrtest.sea.locators.adv_app.lowCollect',
              'com.nrtest.sea.locators.adv_app.newsanswer', 'com.nrtest.sea.locators.adv_app.vipConsMan',
              'com.nrtest.sea.locators.adv_app.vipConsMan.distributedEnergyMange',
              'com.nrtest.sea.locators.adv_app.dataRecover', 'com.nrtest.sea.locators.adv_app.intelligentLock',
              'com.nrtest.sea.locators.adv_app.lineLossAnalysis', 'com.nrtest.sea.locators.adv_app.costControlManage',
              'com.nrtest.sea.locators.adv_app.costControlManage.remoteCustControl',
              'com.nrtest.sea.locators.adv_app.orderedElectricity',
              'com.nrtest.sea.locators.adv_app.transformerMonitor',
              'com.nrtest.sea.locators.adv_app.meteringOnlineMonitor', 'com.nrtest.sea.locators.run_man',
              'com.nrtest.sea.locators.run_man.clock', 'com.nrtest.sea.locators.run_man.groupMan',
              'com.nrtest.sea.locators.run_man.meterMan', 'com.nrtest.sea.locators.run_man.simCardMan',
              'com.nrtest.sea.locators.run_man.operOrganMan', 'com.nrtest.sea.locators.run_man.runStatusMonitor',
              'com.nrtest.sea.locators.sys_mam', 'com.nrtest.sea.locators.sys_mam.logMan',
              'com.nrtest.sea.locators.sys_mam.msgPush', 'com.nrtest.sea.locators.sys_mam.sysUseStat',
              'com.nrtest.sea.locators.sys_mam.securityMan', 'com.nrtest.sea.locators.sys_mam.templateMan',
              'com.nrtest.sea.locators.sys_mam.sysConfigMan', 'com.nrtest.sea.locators.base_app',
              'com.nrtest.sea.locators.base_app.custMan', 'com.nrtest.sea.locators.base_app.archivesMan',
              'com.nrtest.sea.locators.base_app.terminalMan', 'com.nrtest.sea.locators.base_app.interfaceMan',
              'com.nrtest.sea.locators.base_app.dataGatherMan', 'com.nrtest.sea.locators.base_app.multiTableOne',
              'com.nrtest.sea.locators.stat_rey', 'com.nrtest.sea.locators.stat_rey.reportMan',
              'com.nrtest.sea.locators.stat_rey.workQuery', 'com.nrtest.sea.locators.stat_rey.synthQuery',
              'com.nrtest.sea.locators.stat_rey.dataAnalyse', 'com.nrtest.sea.locators.stat_rey.dataAnalyse.loadAanyse',
              'com.nrtest.sea.locators.stat_rey.collConstructStatus', 'com.nrtest.sea.testcase',
              'com.nrtest.sea.testcase.adv_app', 'com.nrtest.sea.testcase.adv_app.appDispose',
              'com.nrtest.sea.testcase.adv_app.lowCollect', 'com.nrtest.sea.testcase.adv_app.newsanswer',
              'com.nrtest.sea.testcase.adv_app.vipConsMan',
              'com.nrtest.sea.testcase.adv_app.vipConsMan.distributedEnergyMange',
              'com.nrtest.sea.testcase.adv_app.dataRecover', 'com.nrtest.sea.testcase.adv_app.intelligentLock',
              'com.nrtest.sea.testcase.adv_app.lineLossAnalysis', 'com.nrtest.sea.testcase.adv_app.costControlManage',
              'com.nrtest.sea.testcase.adv_app.costControlManage.remoteCustControl',
              'com.nrtest.sea.testcase.adv_app.orderedElectricity',
              'com.nrtest.sea.testcase.adv_app.transformerMonitor',
              'com.nrtest.sea.testcase.adv_app.meteringOnlineMonitor', 'com.nrtest.sea.testcase.run_man',
              'com.nrtest.sea.testcase.run_man.clock', 'com.nrtest.sea.testcase.run_man.groupMan',
              'com.nrtest.sea.testcase.run_man.meterMan', 'com.nrtest.sea.testcase.run_man.simCardMan',
              'com.nrtest.sea.testcase.run_man.operOrganMan', 'com.nrtest.sea.testcase.run_man.runStatusMonitor',
              'com.nrtest.sea.testcase.sys_mam', 'com.nrtest.sea.testcase.sys_mam.logMan',
              'com.nrtest.sea.testcase.sys_mam.msgPush', 'com.nrtest.sea.testcase.sys_mam.sysUseStat',
              'com.nrtest.sea.testcase.sys_mam.securityMan', 'com.nrtest.sea.testcase.sys_mam.templateMan',
              'com.nrtest.sea.testcase.sys_mam.sysConfigMan', 'com.nrtest.sea.testcase.base_app',
              'com.nrtest.sea.testcase.base_app.custMan', 'com.nrtest.sea.testcase.base_app.archivesMan',
              'com.nrtest.sea.testcase.base_app.terminalMan', 'com.nrtest.sea.testcase.base_app.interfaceMan',
              'com.nrtest.sea.testcase.base_app.dataGatherMan', 'com.nrtest.sea.testcase.base_app.multiTableOne',
              'com.nrtest.sea.testcase.stat_rey', 'com.nrtest.sea.testcase.stat_rey.reportMan',
              'com.nrtest.sea.testcase.stat_rey.workQuery', 'com.nrtest.sea.testcase.stat_rey.synthQuery',
              'com.nrtest.sea.testcase.stat_rey.dataAnalyse', 'com.nrtest.sea.testcase.stat_rey.dataAnalyse.loadAanyse',
              'com.nrtest.sea.testcase.stat_rey.collConstructStatus', 'com.nrtest.setup', 'com.nrtest.common'],
    package_dir={'': 'src'},
    url='',
    license='',
    author='OSLake',
    author_email='',
    description=''
)
